package view;
import model.kasir;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AUSA
 */
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class casier1 extends javax.swing.JFrame {
    DefaultComboBoxModel <String> mdl = new DefaultComboBoxModel();
    int baris=0;
            static Object [] kolom = {"Barang","Harga","Jumlah","Subtotal"};
            DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
            ArrayList <Integer> data = new ArrayList<>();

    /**
     * Creates new form casier
     */
    public casier1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBarang = new javax.swing.JComboBox<>();
        THarga = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TData = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        spinner = new javax.swing.JSpinner();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Barang");

        jLabel2.setText("Harga");

        jLabel3.setText("Jumlah");

        CBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBarangActionPerformed(evt);
            }
        });

        THarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaActionPerformed(evt);
            }
        });

        BTambah.setText("Beli");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        TData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TData);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("MESIN KASIR");

        TTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTotalActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        spinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spinnerKeyPressed(evt);
            }
        });

        pay.setText("Bayar");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jLabel5.setText("Uang");

        jLabel6.setText("Kembalian");

        jLabel7.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kembalian))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pay)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(jButton1)
                    .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pay)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBarangActionPerformed
       String barang = CBarang.getSelectedItem().toString();
       kasir kasir1 = new kasir();
       String [] pisah = barang.split("-");//("1","PNS")
       String kodeJenis = pisah[0];
       int jenisPegawai = Integer.parseInt(kodeJenis);
       kasir1.setKasir(jenisPegawai);
//       String oke = Integer.toString(kasir1.Harga());
       THarga.setText(kasir1.Harga());
       spinner.setValue(0);
    }//GEN-LAST:event_CBarangActionPerformed

    private void THargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaActionPerformed

    private void TTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTotalActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        mdl.addElement("1-Pensil");
        mdl.addElement("2-Buku");
        mdl.addElement("3-Penggaris");
        mdl.addElement("4-Penghapus");
        mdl.addElement("5-Bulpoin/pcs");
        CBarang.setModel(mdl);
        TData.setModel(tbl);
        THarga.setEditable(false);
        TTotal.setEditable(false);
        kembalian.setEditable(false);
        TTotal.setText("0");
        kembalian.setText("0");
    }//GEN-LAST:event_formComponentShown

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        String Jenis = CBarang.getSelectedItem().toString();//1-PNS
        String [] pisah = Jenis.split("-");//("1","PNS")
        String kodeJenis = pisah[0];
        int jenisPegawai = Integer.parseInt(kodeJenis);
        String jumlah = spinner.getValue().toString();
        int jml2 = Integer.parseInt(jumlah);
        kasir objvoid = new kasir(jml2);
        objvoid.setKasir(jenisPegawai);
        if(THarga.getText().equals("") && jml2 < 1){
        JOptionPane.showMessageDialog(this, "Harap pilih barang", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);  
        }else if(jml2 < 1){            
        JOptionPane.showMessageDialog(this, "Mohon Tentukan Jumlah Barang", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(THarga.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Mohon Pilih Barang Terlebih Dahulu", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);  
        }else{        
//        String satujenis = Integer.toString(objvoid.Jumlah());
//        String banyak = Integer.toString(objvoid.Banyak());
//        String harga = Integer.toString(objvoid.Harga());
        tbl.addRow(new Object [] {objvoid.Nama_barang(), objvoid.Harga(), objvoid.Banyak(), objvoid.printJumlah()});        
        data.add(objvoid.Jumlah());    
        int total = 0;    
        for(int i=0; i<data.size();i++){
        total += data.get(i);
        }
        String Total = Integer.toString(total);
        TTotal.setText(Total);
        TData.setModel(tbl);
        THarga.setText("");
        spinner.setValue(0);
        }        
    }//GEN-LAST:event_BTambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int kol = TData.getSelectedRow();
        if(TData.getRowCount()==0){
        JOptionPane.showMessageDialog(this, "Harus ada barang yang dibeli", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(TData.isRowSelected(kol)){        
        tbl.removeRow(kol);
        data.remove(kol);
        int total = 0;
        for(int i=0; i<data.size(); i++){
            total += data.get(i);
        }
        String Total = Integer.toString(total);
        TTotal.setText(Total);
        }else{
        JOptionPane.showMessageDialog(this, "Pilih barang yang ingin dihapus", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void spinnerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spinnerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerKeyPressed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        //tidak bisa parse karena sistem membaca kosong
        String uang = bayar.getText();
        String total = TTotal.getText();
        if(TTotal.getText().equals("0") && bayar.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Harus ada barang yang dibeli", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(bayar.getText().equals("")){
        JOptionPane.showMessageDialog(this, "masukkan uang anda", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(TTotal.getText().equals("0")){
        JOptionPane.showMessageDialog(this, "Beli dulu baru bayar", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        bayar.setText("");
        }else if(Integer.parseInt(uang) < Integer.parseInt(total)){
        JOptionPane.showMessageDialog(this, "Maaf uang anda kurang", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        bayar.setText("");
        }else{
        int total2 = Integer.parseInt(total);
        int uang2 = Integer.parseInt(uang);
        kasir obj = new kasir();
        kembalian.setText(obj.printJumlah(obj.Jumlah(uang2, total2)));
        JOptionPane.showMessageDialog(this, "Terima Kasih");
        TTotal.setText("0");
        bayar.setText("");
        kembalian.setText("0");
        data.clear();
        tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
        }        
    }//GEN-LAST:event_payActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(casier1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(casier1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(casier1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(casier1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new casier1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CBarang;
    private javax.swing.JTable TData;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField TTotal;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JButton pay;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
